### ISSUE TITLE
Create a logo for the project

### ISSUE THREAD

**Issue by ashishnagpal2498** [ashishnagpal2498/hackstation#1]
You have to create a logo for the project which is
- simple
- attractive
- goes with the concept of project.
Figma design, photoshop files accepted.

**Comment by kcclemo** [comment]
I'd like to work on this, please!

**Comment by ashishnagpal2498** [comment]
Sure. Go on @kcclemo .

**Comment by royquilor** [comment]
Hi, would love to share an idea but the design is based on a font which is - free for personal use. Would that be acceptable?

**Comment by royquilor** [comment]
Hi, I would love to submit a concept?

**Comment by kavita121** [comment]
Heyy!! Can I work on this??

**Comment by kavita121** [comment]
Hey!! I have made a few designs, can I upload a png file I have made it in Illustrator?
