### ISSUE TITLE
Create Header Component

### ISSUE THREAD

**Issue by ashishnagpal2498** [ashishnagpal2498/hackstation#10]
Create a header react component for the project.
The header should be *responsive*. Use **CSS flex boxes** for implementation. 
Refer - 
![HackstationHeader1](https://user-images.githubusercontent.com/36301481/103197737-a31db380-490c-11eb-98d0-caafaf18d0f5.png)
1) OnHover it should show underline. 
2) Use proper tags and Links of react-router-Dom
3) The component file is already present. Make changes to that.
4) Create a new header.css file. Avoid unwanted usage of CSS properties, be precise.

**Comment by anushkasinghal11** [comment]
Can we use reactstrap or material-ui for this?

**Comment by ivaibhavjindal** [comment]
Hi @ashishnagpal2498! I'd like to work on this. Could you illustrate on the point 1 like border bottom only or complete border? Also where should I keep the css file for Navbar or make changes in index.css file only?

**Comment by sanjay270899** [comment]
I want to work on this.

**Comment by ashishnagpal2498** [comment]
@anushkasinghal11 No. For now we'll be using plain CSS only. Would you like to work on this or should I assign it to @ivaibhavjindal .

**Comment by Akshit42-hue** [comment]
I like to work on this issue

**Comment by dsnehasish74** [comment]
I want to work on this please assign this to me.

**Comment by ashishnagpal2498** [comment]
Since, @ivaibhavjindal commented first. I will be assigning it to him.  
Others -> I will be raising more issues soon. You can grab those.

**Comment by Amit366** [comment]
Sir, can I work on this issue?
