### ISSUE TITLE
Create Template for contribution

### ISSUE THREAD

**Issue by ashishnagpal2498** [ashishnagpal2498/hackstation#11]
Create proper template for issue raising and pull request which are submitted to make sure it meets the basic requirements.

1) .github folder - files added -> Issue_template, Pull_request_template.
2) Refer -> https://github.com/vinitshahdeo/Water-Monitoring-System/tree/master/.github

It should display somewhat like this.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by smriti1313** [comment]
Hi, i would like to do this stuff.

**Comment by priyanshi-2508** [comment]
Hello, I want to work on this issue under SWOC.
