### ISSUE TITLE
Contributing.md file and Code_of_conduct.md file 

### ISSUE THREAD

**Issue by akrish4** [ashishnagpal2498/hackstation#12]
Hi @ashishnagpal2498  @kavita121  
I found that your project repository is not having a `contributing.md` file which consists of all contribution guidelines and a `code_of_conduct.md`  file  , I would like to work on this ,  kindly assign me.

**Comment by ashishnagpal2498** [comment]
Please brief about the guidelines you want to add.

**Comment by akrish4** [comment]
@ashishnagpal2498  
the contributing guidlines like
- how to contribute to this repository ie fork , git commands to clone , git commands to push , commit  etc
- always open a issue before opening a PR 
- always follow code of conduct 
all these types of things in a well documented format so that the newbie or beginners who wish to contribute to this repository could follow those guidelines and can understand the git work flow

**Comment by ashishnagpal2498** [comment]
Okay. Add simple steps of how to setup the project (in your language). Go through the project once.

**Comment by akrish4** [comment]
> Okay. Add simple steps of how to setup the project (in your language). Go through the project once.

ok sure @ashishnagpal2498

**Comment by chehak123** [comment]
I would like to work on it under DWOC

**Comment by akrish4** [comment]
#15
