### ISSUE TITLE
Host the Project

### ISSUE THREAD

**Issue by urvashi-code1255** [ashishnagpal2498/hackstation#16]
Hey @ashishnagpal2498 Kindly Host this project so that people who are interested in the project can contribute to it without forking this repo :)
Regards
Urvashi Anand

**Comment by ashishnagpal2498** [comment]
The project has already been hosted on netlify @urvashi-code1255 . There's not much to show, yet I have added the link. When you contribute/ create a PR you will see. Thanks for suggestion.

**Comment by urvashi-code1255** [comment]
Thanks for adding the hosted link in the about :)
