### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by Sloth-Panda** [ashishnagpal2498/hackstation#17]
A little description of Dwoc, hacktoberfest may be added in the readme below their images and also readme  may be attched with links to code_of_conduct and contributing files

**Comment by Sloth-Panda** [comment]
Let me know if this sort of work needs to be done

**Comment by chehak123** [comment]
I would like to work on it

**Comment by ashishnagpal2498** [comment]
I don't think that's really required, just to keep readMe compact, that's all. Appreciate your idea. Go for other issues as well.
