### ISSUE TITLE
Integrate Welcome Bot

### ISSUE THREAD

**Issue by tharunc** [ashishnagpal2498/hackstation#18]
Hello there,
         I can add a welcome bot config file having a proper message that will show up when any user will open up an issue or pull-request for the first time as a part of DWOC. Please assign me this issue.
 For reference, kindly check out: https://github.com/apps/welcome

THANK YOU

**Comment by jatinjain001** [comment]
I want to work on this issue , please let me know if it is available

**Comment by ashishnagpal2498** [comment]
Okay @tharunc . You can work on this issue. Do add a line that kindly check contributing guidelines before working on an issue.
