### ISSUE TITLE
Design homepage for the project

### ISSUE THREAD

**Issue by ashishnagpal2498** [ashishnagpal2498/hackstation#2]
Requirements are as follows.
- Description
- Developer / Organization
- Dashboard
- About
- Contests
This issue is purely based on designing purpose.
Figma or Photoshop.

**Comment by maebasmrt** [comment]
Hi @ashishnagpal2498 ,I wnat to be part of this project

**Comment by ashishnagpal2498** [comment]
Sure, you can start working on the issue. Provide me a PR within two days. Make sure the requirements are fulfilled. 
Design should be simple and satisfy all the points in readme file.

**Comment by Rihanat** [comment]
Hi @ashishnagpal2498 i would like to do this

**Comment by ashishnagpal2498** [comment]
@Rihanat @maebasmrt Its been almost a week ?

**Comment by maebasmrt** [comment]
Appologies @ashishnagpal2498 , I will get back to you before the end of today

**Comment by maebasmrt** [comment]
https://www.figma.com/file/MTFu2wmtN6eH9osiLY3Chi/Hackstation-open-source?node-id=0%3A1

**Comment by maebasmrt** [comment]
Here is my submission @ashishnagpal2498 , Let me know what you think

**Comment by ashishnagpal2498** [comment]
This looks good, 
1. Just remove team section and add something related to dashboard. Providing number of hours, graphs. Something catchy.
2. Also can you change the top most section ? It should be like choose developer or organization, somewhat like it used to be for HackerRank.

**Comment by maebasmrt** [comment]
ok @ashishnagpal2498

**Comment by maebasmrt** [comment]
I will get back to you soon

**Comment by maebasmrt** [comment]
You can now check updates made to the design @ashishnagpal2498

**Comment by ashishnagpal2498** [comment]
By number and graphs I meant, coding activity. Refer this - https://wakatime.com/

**Comment by maebasmrt** [comment]
Oh ok. I understand now

I will get back to you

**Comment by ashishnagpal2498** [comment]
@maebasmrt , still working on this issue? tomorrow is last day for Hacktoberfest. Submit a PR by the end of the day to get merged in Hacktoberfest.

**Comment by antaramunshi** [comment]
@ashishnagpal2498 i'd like to work on this issue if its still open . Also,Can you add the dwoc label as well?

**Comment by ashishnagpal2498** [comment]
Sure @antaramunshi . I hope you have read previous comments + project description and know what requirements I want. Assigning it to you.
You got 5 days to complete it.
Keep in mind, your first PR is not supposed to be the best but a starting point for meeting the requirements, so do not wait until 5 days to show your work. Keep pushing your commits and getting feedback.

**Comment by antaramunshi** [comment]
@ashishnagpal2498 do i need to create just the wireframe ? I can do the entire homepage frontend part as well.

**Comment by ashishnagpal2498** [comment]
>
> @ashishnagpal2498 do i need to create just the wireframe ? I can do the entire homepage frontend part as well.
You just need to create the wireframe. This issue is totally based on designing. Use figma/ psd whichever you feel comfortable.

**Comment by antaramunshi** [comment]
@ashishnagpal2498 i've done the design but how am i supposed to create a PR for this issue. Like here i don't need to change files. Just the Figma link is supposed to be attached

**Comment by antaramunshi** [comment]
https://www.figma.com/file/US60kwcKQ5jWGZKlTfI8xs/HackStation?node-id=0%3A1

**Comment by yashsehgal** [comment]
Hey, Can I work on this issue?

**Comment by kanishkaa24** [comment]
Hey!
I would love to work on this issue.

**Comment by ashishnagpal2498** [comment]
@antaramunshi , your link isn't working. Kindly check that asap.

**Comment by antaramunshi** [comment]
https://www.figma.com/file/US60kwcKQ5jWGZKlTfI8xs/HackStation?node-id=0%3A1     Its working for me tho

**Comment by ashishnagpal2498** [comment]
Okay @kanishkaa24 , @yashsehgal . Go ahead. Please read the project description thoroughly  and the chats above. Then come up with something different. 
I need dashboard, profile selection (whether the person is developer/ org) , charts to be shown. 
I already have this design -  https://www.figma.com/file/MTFu2wmtN6eH9osiLY3Chi/Hackstation-open-source?node-id=0%3A1
Do it accordingly.

**Comment by yashsehgal** [comment]
> Okay @kanishkaa24 , @yashsehgal . Go ahead. Please read the project description thoroughly and the chats above. Then come up with something different.
> I need dashboard, profile selection (whether the person is developer/ org) , charts to be shown.
> I already have this design - https://www.figma.com/file/MTFu2wmtN6eH9osiLY3Chi/Hackstation-open-source?node-id=0%3A1
> Do it accordingly.
> Reference - https://wakatime.com/ , hackerrank

Sure!

**Comment by nehaparmar99** [comment]
Can I work on it?

**Comment by ashishnagpal2498** [comment]
No updates ? @yashsehgal @kanishkaa24 @antaramunshi .

**Comment by ashishnagpal2498** [comment]
> Can I work on it?

Yes @nehaparmar99 Please. 2 days ? I want it asap. Refer to previous chat. You'll get to know the requirement.

**Comment by nehaparmar99** [comment]
Hey, I thought the issue was related to coding.I won't be able to do it.
