### ISSUE TITLE
Automating project

### ISSUE THREAD

**Issue by himanshu007-creator** [ashishnagpal2498/hackstation#20]
I would like to work on this issue.I will create a script that will enable opening website from CLI.
Please add DWOC label to it and assign me this issue.

**Comment by ashishnagpal2498** [comment]
You mean to say adding concurrently script line to run frontend and backend ?

**Comment by himanshu007-creator** [comment]
> You mean to say adding concurrently script line to run frontend and backend ?

No!
I mean to say a simple script, that will open your website, the one in the description of repo.

**Comment by ashishnagpal2498** [comment]
I didn't get the purpose. If you want to run locally - use npm start or use URL for project. Why do you want to add script for URL ?

**Comment by himanshu007-creator** [comment]
> I didn't get the purpose. If you want to run locally - use npm start or use URL for project. Why do you want to add script for URL ?

Sir, script will increase efficiency by reducing surfing time.

**Comment by ashishnagpal2498** [comment]
Surfing time ? As in if developers are working on the project, they'll be knowing the project URL right, through project description ? Why script ? - URL is mainly for users.

**Comment by himanshu007-creator** [comment]
> Surfing time ? As in if developers are working on the project, they'll be knowing the project URL right, through project description ? Why script ? - URL is mainly for users.

Developers/users who will be using ubuntu will find running script easier. They won't have to spend time in copy pasting whole url. Just run the script, WHAM!! there you go

**Comment by ashishnagpal2498** [comment]
I appreciate your effort. But I don't find any relevance about it. Sorry about that. I hope you understand. Keep contributing and raising new issues :)
