### ISSUE TITLE
README BADGES AND HEADING OF PROJECT 

### ISSUE THREAD

**Issue by akrish4** [ashishnagpal2498/hackstation#22]
Hi @ashishnagpal2498 

I found that the README file is not havinga heading or title of the project 
I would be glad if you can assign me this issue , I can add title and add badges also and align everything center 

Let me know if you are interested 

![readme1](https://user-images.githubusercontent.com/61831021/104603997-faf54200-56a2-11eb-93e0-4b2a0e81ed19.PNG)

The above image is the badges I am talking about , it will be similar to it

**Comment by ashishnagpal2498** [comment]
Please add badges and heading in a single PR. If you add something else too, let me know I'll upgrade the level. Make it as attractive as possible. I am closing the other issue. Please avoid creating multiple similar kind of issues.

**Comment by akrish4** [comment]
> Please add badges and heading in a single PR. If you add something else too, let me know I'll upgrade the level, accordingly if I feel a genuine change. Make it as attractive as possible. I am closing the other issue. Please avoid creating multiple similar kind of issues.

yes sure I will add both in a single pr , Let me which similar issue you are talking abt ? I didn't get u , I have opened one issue for pr template earlier thatsall
