### ISSUE TITLE
Add logo and user icon to header

### ISSUE THREAD

**Issue by ashishnagpal2498** [ashishnagpal2498/hackstation#24]
Add logo to the navbar. Also add the user sign instead of login/signup text.
![header_Hackstation](https://user-images.githubusercontent.com/36301481/104613883-b15e2480-56ad-11eb-958d-f1616e09b4ae.png)
![hackstationLogo2](https://user-images.githubusercontent.com/36301481/104613985-cb980280-56ad-11eb-9eae-a4d43bc02a5b.png)

**Comment by shravani05** [comment]
@ashishnagpal2498 I would like to work on this issue. I am part of SWOC 2021.

**Comment by nehaparmar99** [comment]
Can I work on this?I'm a participant in SWOC'21.

**Comment by Ayushgup85** [comment]
Can i work on this issue?

**Comment by shravani05** [comment]
@ashishnagpal2498 I have solved this issue by adding the logo and replacing the login/sign text with a user icon. 
The UI looks as follows:
![ui](https://user-images.githubusercontent.com/43898702/104836377-93720900-58d3-11eb-9785-13208280b8bf.png)

Please let me know if further changes are required.

**Comment by ashishnagpal2498** [comment]
Just remove the text "Hackstation" as logo has it. Also if you have used image for user. Please don't use that, instead add icon using font-awesome, add CDN in index.html.

**Comment by shravani05** [comment]
Okay, will do that.

**Comment by shravani05** [comment]
@ashishnagpal2498 sorry for the delay. I have made the necessary changes and created pr #33  
Please let me know if any further changes are required.
