### ISSUE TITLE
Check for Templates

### ISSUE THREAD

**Issue by ashishnagpal2498** [ashishnagpal2498/hackstation#25]
There is a small error, due to which the templates are not showing. Rectify the error and solve.
Reference https://github.com/vinitshahdeo/Water-Monitoring-System/tree/master/.github

**Comment by muthuannamalai12** [comment]
I would love to work on this issue as a part of DWOC. Kindly assign me

**Comment by kanishkaa24** [comment]
@ashishnagpal2498 Can I work on this?

**Comment by muthuannamalai12** [comment]
@ashishnagpal2498 Can you please remove SWOC and add DWOC label and the level label of my issue
