### ISSUE TITLE
Create a Footer

### ISSUE THREAD

**Issue by ashishnagpal2498** [ashishnagpal2498/hackstation#26]
Create an attractive footer for the project. Use logo -> 
![hackstationLogo](https://user-images.githubusercontent.com/36301481/104619223-a0b0ad00-56b3-11eb-84ce-9b845b1729b5.png)
- It should be responsive. 
- Use flex boxes. (strictly, easy implementation)
- Avoid copying code.

**Comment by AbhipsaGuru1012** [comment]
@ashishnagpal2498 can I work on this issue?

**Comment by nehaparmar99** [comment]
Can I work on it?

**Comment by AbhipsaGuru1012** [comment]
![footerPull](https://user-images.githubusercontent.com/58511560/104718252-9abcd980-5750-11eb-98eb-455e635de0a1.PNG)

Hi @ashishnagpal2498 please let me know if this Footer is okay. Thanks!

**Comment by kanishkaa24** [comment]
@ashishnagpal2498 Can I work on this issue ?

**Comment by ashishnagpal2498** [comment]
1) Just Add the logo and make that as link to homepage
2) Add Subscribe tab in center
3) Icons should be aligned horizontally.
Does that look good to you ?

**Comment by AbhipsaGuru1012** [comment]
> 1. Just Add the logo and make that as link to homepage
> 2. Add Subscribe tab in center
> 3. Icons should be aligned horizontally.
>    Does that look good to you ?

Thank you, I will make the changes and get back soon.

**Comment by AbhipsaGuru1012** [comment]
![footer-new](https://user-images.githubusercontent.com/58511560/104809091-bedfef80-5810-11eb-9040-39cbaf38e94a.PNG)

@ashishnagpal2498 is this footer okay?

**Comment by ashishnagpal2498** [comment]
You aren't creating a Footer component. Just the design?

**Comment by AbhipsaGuru1012** [comment]
> You aren't creating a Footer component. Just the design?

@ashishnagpal2498 this a footer component.

**Comment by ashishnagpal2498** [comment]
Okay.. just submit a PR then.

**Comment by achalesh27022003** [comment]
Please assign me this issue @ashishnagpal2498 sir.

**Comment by vismitap** [comment]
Hey! May I work on this issue?

**Comment by anushavc** [comment]
can i work on this issue?

**Comment by ashishnagpal2498** [comment]
@nehaparmar99 , @kanishkaa24 would you like to work on this issue?

**Comment by kanishkaa24** [comment]
> @nehaparmar99 , @kanishkaa24 would you like to work on this issue?

Definitely

**Comment by nehaparmar99** [comment]
> @nehaparmar99 , @kanishkaa24 would you like to work on this issue?

Yes I'd like to

**Comment by ashishnagpal2498** [comment]
Since @nehaparmar99 opted for issue, before @kanishkaa24 . Hence Assigning it to you. 2 days to submit a PR. Please use flex boxes well.

**Comment by ashishnagpal2498** [comment]
Since DWOC is about to end. Try to submit a PR asap. @kanishkaa24

**Comment by kanishkaa24** [comment]
> Since DWOC is about to end. Try to submit a PR asap. @kanishkaa24

What all components are required?

**Comment by dollyjain51099** [comment]
I would like to work on this issue, @ashishnagpal2498 kindly assign it to me!

**Comment by ashishnagpal2498** [comment]
Swoc21 last day tomorrow. Submit a PR by the end of day. @dollyjain51099 assigned. Please refer to previous chat. Responsive, flex boxes. No extra CSS.

**Comment by ashishnagpal2498** [comment]
@dollyjain51099 update?
