### ISSUE TITLE
Adding splash screen 

### ISSUE THREAD

**Issue by Vrushti24** [ashishnagpal2498/hackstation#27]
I think adding splash screen can look website more attractive.
@ashishnagpal2498

**Comment by Vrushti24** [comment]
I would love to take this issue

**Comment by ashishnagpal2498** [comment]
What do you mean by splashing screen ? any demo ? Please share.

**Comment by Vrushti24** [comment]
A start screen which shows name or logo of ur website for 3-5 second then
ur main page can be seen how about that I have made such screen in flutter
I don't have any demo for html but I can make on that

**Comment by Vrushti24** [comment]
It's kind of start screen

**Comment by Vrushti24** [comment]
@ashishnagpal2498  did u thought about this?

**Comment by aum-singhal** [comment]
I can do this.
We can make a svg file of the logo and then animate it.
I will be contributing under SWoC 2021

**Comment by aum-singhal** [comment]
https://user-images.githubusercontent.com/69421286/105950994-6244c600-6095-11eb-8844-f3130923710e.mp4

For example you need something like this??

**Comment by ashishnagpal2498** [comment]
I got what you are trying to add. But all these things are additional. Currently my focus is to work on project basics.

**Comment by Vrushti24** [comment]
Okay no problem 👍

**Comment by aum-singhal** [comment]
Can i work on this ??
