### ISSUE TITLE
Upcoming Contest Card Component

### ISSUE THREAD

**Issue by ashishnagpal2498** [ashishnagpal2498/hackstation#35]
## 🚀 Feature

- Strictly based on CSS flexboxes.
- Responsive, react component
- Display on homepage

Open to innovation and suggestions
Sample Design 
![Hackstation2](https://user-images.githubusercontent.com/36301481/106901446-c6aef780-671d-11eb-8a74-c2e344e97e62.png)

**Comment by sanjay270899** [comment]
@ashishnagpal2498 I would Like to work on this.

**Comment by ashishnagpal2498** [comment]
Assigned. @sanjay270899 Submit a PR in 2 days.
