### ISSUE TITLE
Sign Up component

### ISSUE THREAD

**Issue by ashishnagpal2498** [ashishnagpal2498/hackstation#39]
## 🚀 Feature

- Sign up form
-  should be responsive
- Proper Html tags
- Open to innovation 
- Use simple CSS only.

**Comment by Kathuria** [comment]
@ashishnagpal2498 : Can I work on this?

**Comment by ashishnagpal2498** [comment]
Assigned. 2 days, submit a PR.

**Comment by Kathuria** [comment]
@ashishnagpal2498 : Please review the PR

**Comment by Kathuria** [comment]
@ashishnagpal2498 : Incorporated Review Comments, Please have a look.

**Comment by Kathuria** [comment]
@ashishnagpal2498 : Can You please check latest changes, incorporated all review comments. If looks good please merge and close this task.
Thanks.
