### ISSUE TITLE
Color code and Typography for the project

### ISSUE THREAD

**Issue by ashishnagpal2498** [ashishnagpal2498/hackstation#4]
Define color codes and fonts to be used for the project. 
This issue is purely based for UX researcher. Provide the reasons for choosing color codes.

**Comment by utchak160** [comment]
@ashishnagpal2498 Please assign this to me.

**Comment by utchak160** [comment]
I've to add the variables of the color code? As then it would be in scss and the project is setup for css.

**Comment by ashishnagpal2498** [comment]
No, Just mention the color codes in json file and all the fonts. Also when you provide the PR, do mention the reason of choosing such colors and fonts. Add links for viewing.

**Comment by utchak160** [comment]
https://coolors.co/7400b8-6930c3-5e60ce-5390d9-4ea8de-48bfe3-56cfe1-64dfdf-72efdd-80ffdb
According to me, this color palette will best be suited for this use case because it has a smooth mixture and the user will like to see the page so as to track his or her coding hours regularly. Please tell me your views.

**Comment by antaramunshi** [comment]
32,194,14 RGB with a black bg would look actually cool since it's a coding status bar. We can also keep a light mode for those who would like to work in  the light mode. And ig Lato as a font would enhance the page. I think i'll be able to work on this. Can you assign this to me?

**Comment by himanshu007-creator** [comment]
i would like to work on this issue. Please assign me this issue.

**Comment by ashishnagpal2498** [comment]
@antaramunshi . Since you are designing homepage. Assigning this to @himanshu007-creator 
Please provide a relevant color code, fonts. I want you to explore different webpages and then come up with something providing the reason for choosing. You can attach links for sites you visit.

**Comment by himanshu007-creator** [comment]
SIR, as we are making a website that will track number of hours of coding, we need to focus on coders.I would suggest to use dark themed background as mostly coders code at night. But using green color for text is TOO MUCH predictable!
For that i suggest, we will use orange color.
and for font, we will use OSWALD font [ light 300 varient]

so i finally propose these:-
background color:- black
text color [for headings]:- #ff7b00 
font [for heading]:-Source Sans Pro
text color :- white
font [for text]:-Oswald [light 300 varient]
other colors( for image background, etc):- #907163, #3a9e66,

implementing these changes, our website will be similar to this one
![COLOR SCHEME](https://user-images.githubusercontent.com/65963997/103339878-a188f280-4aa8-11eb-851d-f07621ded9cf.jpg)

**Comment by himanshu007-creator** [comment]
@ashishnagpal2498  Sir, i have suggested color code and Typography. What next?

**Comment by ashishnagpal2498** [comment]
Add these configs which you have selected in App.css and submit a PR.

**Comment by himanshu007-creator** [comment]
> Add these configs which you have selected in App.css and submit a PR.

Hi sir, can i  add a separate css file of proposed changes?

**Comment by ashishnagpal2498** [comment]
Sure. Submit a PR asap.
