### ISSUE TITLE
Amcharts Homepage component

### ISSUE THREAD

**Issue by ashishnagpal2498** [ashishnagpal2498/hackstation#40]
## 🚀 Feature

Create a component and divide into two parts horizontally -
1. Includes number of hours code - Line chart ( as shown in image)
2. Pie chart -> Shows different languages ( enter random values , HTML, CSS, JS , C++)
![WhatsApp Image 2021-02-07 at 10 00 33 PM](https://user-images.githubusercontent.com/36301481/107152826-1c8ad600-6990-11eb-9523-131be9007e1f.jpeg)
- Responsive and open to innovation. Ref - https://wakatime.com/dashboard

**Comment by sanjay270899** [comment]
@ashishnagpal2498 I would Like to work on this.

**Comment by ashishnagpal2498** [comment]
Assigned. 2 days. Come up with something different.
