### ISSUE TITLE
MongoDB Backend

### ISSUE THREAD

**Issue by ashishnagpal2498** [ashishnagpal2498/hackstation#41]
## 🚀 Feature

Backend issue - Setup MongoDB and mongoose for the project.

**Comment by nehaparmar99** [comment]
Can I work on it?

**Comment by ashishnagpal2498** [comment]
Assigned. Submit a PR by tomorrow.

**Comment by nehaparmar99** [comment]
@ashishnagpal2498 just wanted to know if I should setup mongoDB community version which requires the interface or mongoDB atlas?

**Comment by nehaparmar99** [comment]
@ashishnagpal2498 I've setup a mongoDB atlas connection.You'll have to add your credentials in the variables.json file in config folder.

**Comment by nehaparmar99** [comment]
Also, I'll be getting points under both SWOC and DWOC for it right?

**Comment by ashishnagpal2498** [comment]
Done. Great 👍
