### ISSUE TITLE
Create User schema 

### ISSUE THREAD

**Issue by ashishnagpal2498** [ashishnagpal2498/hackstation#42]
## 🚀 Feature

- Backend Issue. Take pull from backend branch
- Setup User Schema. Issue to be done after #41

**Comment by tirlochanarora16** [comment]
@ashishnagpal2498, what properties are to be included in the user schema?

**Comment by ashishnagpal2498** [comment]
Email, username, Name, organization, bio, GitHub and LinkedIn profile link, phone number. Rest you can add accordingly.
Password should be separate schema (use bcrypt to encrypt it).

PS:- Let it be behind. I'll look into it. Also SWOC21 last day tomorrow. Submit a PR by end of day.

**Comment by tirlochanarora16** [comment]
Can I use the mongoose library for creating Schema? @ashishnagpal2498

**Comment by ashishnagpal2498** [comment]
Ya ya go ahead.

**Comment by tirlochanarora16** [comment]
Hey it's showing a 403 forbidden error while I try to push my branch. @ashishnagpal2498

**Comment by ashishnagpal2498** [comment]
Did you fork the repository ? I hope you are submitting a PR correctly.

**Comment by tirlochanarora16** [comment]
@ashishnagpal2498 sorry I forgot to fork the repository, do you still require a PR or the project is submitted for SWOC?

**Comment by ashishnagpal2498** [comment]
Yes you can submit till end of the day.

**Comment by tirlochanarora16** [comment]
created PR for user schema @ashishnagpal2498

**Comment by FreelancerAnkit** [comment]
@ashishnagpal2498 , I have created Userschema for this, i will create a PR for same. Please check it.
