### ISSUE TITLE
Add a contributors table in readme

### ISSUE THREAD

**Issue by himanshu007-creator** [ashishnagpal2498/hackstation#47]
## 🚀 Feature

I would like to add a contributor's table in readme
----
- I would like to add a contributor's table in readme

**Describe the solution you'd like**
----
- I would work on it

**Describe alternatives you've considered**
----
- A clear and concise description of any alternative solutions or features you've considered.

**Additional context**
----
- Please add DWOC and level-2 tags

**Comment by ashishnagpal2498** [comment]
Start working. 1 day to submit a PR.
