### ISSUE TITLE
Create About Page

### ISSUE THREAD

**Issue by ashishnagpal2498** [ashishnagpal2498/hackstation#51]
## 🚀 Feature

**Is your feature request related to a problem? Please describe.**
----
- Create an about component for the project.
- Link that to the route
- Responsive and attractive design

**Comment by Aniket118** [comment]
I would like to work on this issue! @ashishnagpal2498

**Comment by ashishnagpal2498** [comment]
Assigned. Make sure you fulfill the requirements.
Submit a PR by the end of the day. Since tomorrow is last day for Swoc21

**Comment by nawed2611** [comment]
Is this issue still open?

**Comment by ashishnagpal2498** [comment]
Yes, it is open. You can work on it @nawed2611 .

**Comment by nawed2611** [comment]
Can you let me know what all to include on the page? And would it be counted as a SWOC contribution?

**Comment by ashishnagpal2498** [comment]
> Can you let me know what all to include on the page? And would it be counted as a SWOC contribution?
Yes, so include the content of the project description along with your innovation....

**Comment by Shofiya2003** [comment]
Hello. If this issue is still nor resolved can I work on this issue as a part of SWOC 2021? Thanks a ton.

**Comment by aakankshabhende** [comment]
Any updates? @nawed2611

**Comment by nawed2611** [comment]
Working on it! Was a bit busy due to exams.

**Comment by aakankshabhende** [comment]
No worries :) @nawed2611 . But try to make PR soon.

**Comment by nawed2611** [comment]
#60 
I have submitted a PR for the issue. I'm fairly new to open-source so apologies if I made any mistakes in writing the PR message 😅.  I have tried to make the About page look consistent with the website with some UI changes.

**Comment by aakankshabhende** [comment]
No problem do tell if you face any issues in making PR
