### ISSUE TITLE
Adding a footer

### ISSUE THREAD

**Issue by sn2606** [ashishnagpal2498/hackstation#55]
## 🚀 Footer

**Footer is not visible/Implemented**
----
- In all the pages, footer component is not visible.

**Implementing footer**
----
- I would like to add a footer component with links to other pages

**Alternatives**
----
- None considered, since footer idea is already included in website.

**Additional context**
----
- This is how it looks right now
![image](https://user-images.githubusercontent.com/58822437/145158434-dd686246-aca1-4ac4-9473-73905d12710b.png)

**Comment by ashishnagpal2498** [comment]
Hi @sn2606, Thank you for raising this issue. Yes you can start working on it. Please come up with a different design.

**Comment by Shofiya2003** [comment]
Hello. Can I work on this issue?

**Comment by aakankshabhende** [comment]
Any updates? @sn2606

**Comment by sn2606** [comment]
> Any updates? @sn2606

Hello, yes I am almost done, I am sorry for being late, I was swamped by end-of-semester exams. I will open the PR in at most 3 days.

**Comment by aakankshabhende** [comment]
No worries :) @sn2606
