### ISSUE TITLE
Responsive Header

### ISSUE THREAD

**Issue by ashishnagpal2498** [ashishnagpal2498/hackstation#56]
## 🐛 Bug Report

**Describe the bug**
----
- The header is not responsive for mobile screen sizes.

**Expected behavior**
-----
- Create the header responsive. Currently all the Navbar items shown in mobile size. create a dropdown.

**Screenshots**
----
- Currently

![image](https://user-images.githubusercontent.com/36301481/145793340-699c63b8-df9d-45cf-bdb4-3bf78fd84fd9.png)

- Expected
![header_mobileview](https://user-images.githubusercontent.com/36301481/145793425-1a136edf-233f-430a-9377-2c7f63d350b7.jpg)

**Additional context**
----
- Advisable, not to create it from scratch.

**Comment by Reckon77** [comment]
Hi there, I would like to work on this issue

**Comment by Inrmanish** [comment]
plz see my pull req.
