### ISSUE TITLE
DWOC issue

### ISSUE THREAD

**Issue by smriti1313** [ashishnagpal2498/hackstation#9]
Hello, I cannot see any issue under DWOC label. I guess your project is a part of projects provided by DWOC2020. I guess you forgot to add label or something. Kindly check to that.

**Comment by ashishnagpal2498** [comment]
I was about to add. Thanks for reminder @smriti1313 .

**Comment by ProPratik1405** [comment]
I want to Work On this Project. Can You Please Assign Me a Task
